name: flutter_survey_app_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Core
  dartz: ^0.10.1 # Functional programming library for Dart
  easy_localization: ^3.0.7 # Simplifies localization and internationalization of the app
  get_it: ^7.7.0 # Service locator for dependency injection
  provider: ^6.1.2 # State management library
  mockito: ^5.4.4 # Used to test the app and improve the code quality
  equatable: ^2.0.5 # used to prevent object reference shifts
  share_plus: ^10.0.2 # Enables sharing content from the app to other applications
  url_launcher: ^6.3.0 # Launches URLs in a web browser or another app
  uuid: ^4.5.0 # Generates unique IDs for objects or entities
  intl: ^0.19.0 # Provides internationalization and localization facilities
  image_cropper: ^8.0.2 # Allows cropping of images
  flutter_svg: ^2.0.10+1 # Renders SVG (Scalable Vector Graphics) files
  image_picker: ^1.1.2 # Enables image picking from gallery or camera
  internet_connection_checker_plus: ^2.5.2 # Checks for active internet connections

  # Firebase
  firebase_core: ^3.5.0 # Used to initialize and configure Firebase services in the application.
  cloud_firestore: ^5.4.2 # Used for cloud database services.
  firebase_storage: ^12.3.1 # Used for file storage and management.

  # UI
  cupertino_icons: ^1.0.6 # Cupertino style icons for iOS design
  font_awesome_flutter: ^10.7.0 # Provides Font Awesome icons for Flutter
  google_fonts: ^6.2.1 # Allows the use of fonts from Google Fonts
  flutter_speed_dial: ^7.0.0 # Creates floating action buttons with a speed dial effect
  flutter_staggered_grid_view: ^0.7.0 # Provides staggered grid layouts for Flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3 # Build system for Dart to generate code
  json_serializable: ^6.8.0 # Code generator for JSON serialization
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
  
