name: flutter_survey_app_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase


  equatable: ^2.0.5 # used to prevent object reference shifts
  easy_localization: ^3.0.7
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  json_serializable: ^6.8.0
  image_cropper: ^8.0.2
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  get_it: ^7.7.0
  uuid: ^4.5.0
  intl: ^0.19.0
  flutter_speed_dial: ^7.0.0
 
  # Cache
  hive: ^2.2.3 # A fast and lightweight NoSQL database for local data storage
  hive_flutter: ^1.1.0 # Provides simple and secure data storage with Hive in Flutter applications
  encrypt: ^5.0.3 # Used for data encryption
  flutter_secure_storage: ^9.2.2 # Secure storage for sensitive data (e.g., encrypted data)
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  mockito: ^5.4.4 
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  overflow_view: ^0.3.1
  flutter_svg: ^2.0.10+1
  image_picker_for_web: ^3.0.5
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3 # Build system for Dart to generate code
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/

  
